######################################################################
# Automatically generated by qmake (3.0) Sun Jan 4 21:13:08 2015
######################################################################

QT += testlib
TEMPLATE = app
TARGET = tests
INCLUDEPATH += . ../core

# Input
SOURCES += tester.cpp ../core/indicator.cpp
HEADERS += ../core/indicator.hpp
